package analyzer

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "analyzer",
		Actions: []model.ActionDefinition{
			{
				ID:          "analyzer.discover-device",
				Name:        "discover device",
				Kind:        model.ObserveAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"campaign.accept-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "analyzer.open-session",
				Name:        "open session",
				Kind:        model.ControlAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.discover-device"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.negotiate-protocol",
				Name:        "negotiate protocol",
				Kind:        model.ProtectAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.open-session"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.request-sample",
				Name:        "request sample",
				Kind:        model.RecoverAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.negotiate-protocol"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "analyzer.receive-frame",
				Name:        "receive frame",
				Kind:        model.ObserveAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.request-sample"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.validate-sequence",
				Name:        "validate sequence",
				Kind:        model.ControlAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.receive-frame"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.normalize-composition",
				Name:        "normalize composition",
				Kind:        model.ProtectAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.validate-sequence"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "analyzer.publish-reading",
				Name:        "publish reading",
				Kind:        model.RecoverAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.normalize-composition"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.track-latency",
				Name:        "track latency",
				Kind:        model.ObserveAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.publish-reading"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.retry-request",
				Name:        "retry request",
				Kind:        model.ControlAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.track-latency"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "analyzer.expire-attempt",
				Name:        "expire attempt",
				Kind:        model.ProtectAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.retry-request"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.degrade-source",
				Name:        "degrade source",
				Kind:        model.RecoverAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.expire-attempt"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.restore-source",
				Name:        "restore source",
				Kind:        model.ObserveAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.degrade-source"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "analyzer.close-session",
				Name:        "close session",
				Kind:        model.ControlAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.restore-source"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.archive-reading",
				Name:        "archive reading",
				Kind:        model.ProtectAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.close-session"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.renew-calibration",
				Name:        "renew calibration",
				Kind:        model.RecoverAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.archive-reading"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "analyzer.audit-sample",
				Name:        "audit sample",
				Kind:        model.ObserveAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.renew-calibration"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "analyzer.publish-health",
				Name:        "publish health",
				Kind:        model.ControlAction,
				Equipment:   "gas-analyzer",
				Requires:    []string{"analyzer.audit-sample"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
