package feed

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "feed",
		Actions: []model.ActionDefinition{
			{
				ID:          "feed.sample-header",
				Name:        "sample header",
				Kind:        model.ObserveAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"campaign.accept-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "feed.verify-hydrogen",
				Name:        "verify hydrogen",
				Kind:        model.ControlAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.sample-header"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.verify-nitrogen",
				Name:        "verify nitrogen",
				Kind:        model.ProtectAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.verify-hydrogen"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.balance-ratio",
				Name:        "balance ratio",
				Kind:        model.RecoverAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.verify-nitrogen"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "feed.open-block-valve",
				Name:        "open block valve",
				Kind:        model.ObserveAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.balance-ratio"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.prime-header",
				Name:        "prime header",
				Kind:        model.ControlAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.open-block-valve"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.stabilize-pressure",
				Name:        "stabilize pressure",
				Kind:        model.ProtectAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.prime-header"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "feed.authorize-compressor",
				Name:        "authorize compressor",
				Kind:        model.RecoverAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.stabilize-pressure"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.track-consumption",
				Name:        "track consumption",
				Kind:        model.ObserveAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.authorize-compressor"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.trim-flow",
				Name:        "trim flow",
				Kind:        model.ControlAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.track-consumption"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "feed.isolate-feed",
				Name:        "isolate feed",
				Kind:        model.ProtectAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.trim-flow"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.depressurize-header",
				Name:        "depressurize header",
				Kind:        model.RecoverAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.isolate-feed"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.restore-header",
				Name:        "restore header",
				Kind:        model.ObserveAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.depressurize-header"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "feed.verify-seal",
				Name:        "verify seal",
				Kind:        model.ControlAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.restore-header"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.publish-permit",
				Name:        "publish permit",
				Kind:        model.ProtectAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.verify-seal"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.archive-sample",
				Name:        "archive sample",
				Kind:        model.RecoverAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.publish-permit"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "feed.renew-permit",
				Name:        "renew permit",
				Kind:        model.ObserveAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.archive-sample"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "feed.close-permit",
				Name:        "close permit",
				Kind:        model.ControlAction,
				Equipment:   "synthesis-feed-header",
				Requires:    []string{"feed.renew-permit"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
