package separator

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "separator",
		Actions: []model.ActionDefinition{
			{
				ID:          "separator.accept-condensate",
				Name:        "accept condensate",
				Kind:        model.ObserveAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"cooling.publish-cooling"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "separator.measure-pressure",
				Name:        "measure pressure",
				Kind:        model.ControlAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.accept-condensate"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.measure-level",
				Name:        "measure level",
				Kind:        model.ProtectAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.measure-pressure"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.verify-density",
				Name:        "verify density",
				Kind:        model.RecoverAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.measure-level"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "separator.settle-product",
				Name:        "settle product",
				Kind:        model.ObserveAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.verify-density"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.open-product",
				Name:        "open product",
				Kind:        model.ControlAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.settle-product"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.transfer-ammonia",
				Name:        "transfer ammonia",
				Kind:        model.ProtectAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.open-product"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "separator.close-product",
				Name:        "close product",
				Kind:        model.RecoverAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.transfer-ammonia"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.drain-water",
				Name:        "drain water",
				Kind:        model.ObserveAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.close-product"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.protect-high-level",
				Name:        "protect high level",
				Kind:        model.ControlAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.drain-water"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "separator.protect-low-pressure",
				Name:        "protect low pressure",
				Kind:        model.ProtectAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.protect-high-level"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.equalize-vessel",
				Name:        "equalize vessel",
				Kind:        model.RecoverAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.protect-low-pressure"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.isolate-vessel",
				Name:        "isolate vessel",
				Kind:        model.ObserveAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.equalize-vessel"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "separator.restore-inventory",
				Name:        "restore inventory",
				Kind:        model.ControlAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.isolate-vessel"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.publish-product",
				Name:        "publish product",
				Kind:        model.ProtectAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.restore-inventory"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.archive-transfer",
				Name:        "archive transfer",
				Kind:        model.RecoverAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.publish-product"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "separator.renew-drain-permit",
				Name:        "renew drain permit",
				Kind:        model.ObserveAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.archive-transfer"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "separator.release-vessel",
				Name:        "release vessel",
				Kind:        model.ControlAction,
				Equipment:   "liquid-ammonia-separator",
				Requires:    []string{"separator.renew-drain-permit"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
