package purge

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "purge",
		Actions: []model.ActionDefinition{
			{
				ID:          "purge.read-loop-composition",
				Name:        "read loop composition",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"separator.publish-product"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "purge.calculate-inerts",
				Name:        "calculate inerts",
				Kind:        model.ControlAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.read-loop-composition"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.select-header",
				Name:        "select header",
				Kind:        model.ProtectAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.calculate-inerts"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.plan-valves",
				Name:        "plan valves",
				Kind:        model.RecoverAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.select-header"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "purge.reserve-actuators",
				Name:        "reserve actuators",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.plan-valves"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.move-valve-one",
				Name:        "move valve one",
				Kind:        model.ControlAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.reserve-actuators"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.move-valve-two",
				Name:        "move valve two",
				Kind:        model.ProtectAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.move-valve-one"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "purge.move-valve-three",
				Name:        "move valve three",
				Kind:        model.RecoverAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.move-valve-two"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.verify-positions",
				Name:        "verify positions",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.move-valve-three"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.reconcile-partial",
				Name:        "reconcile partial",
				Kind:        model.ControlAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.verify-positions"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "purge.publish-purge",
				Name:        "publish purge",
				Kind:        model.ProtectAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.reconcile-partial"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.hold-inerts",
				Name:        "hold inerts",
				Kind:        model.RecoverAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.publish-purge"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.close-valves",
				Name:        "close valves",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.hold-inerts"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "purge.release-actuators",
				Name:        "release actuators",
				Kind:        model.ControlAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.close-valves"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.restore-plan",
				Name:        "restore plan",
				Kind:        model.ProtectAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.release-actuators"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.archive-plan",
				Name:        "archive plan",
				Kind:        model.RecoverAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.restore-plan"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "purge.renew-plan",
				Name:        "renew plan",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.archive-plan"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "purge.audit-emissions",
				Name:        "audit emissions",
				Kind:        model.ControlAction,
				Equipment:   "recycle-gas-purge",
				Requires:    []string{"purge.renew-plan"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
