package steam

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "steam",
		Actions: []model.ActionDefinition{
			{
				ID:          "steam.accept-hot-effluent",
				Name:        "accept hot effluent",
				Kind:        model.ObserveAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"converter.admit-synthesis-gas"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "steam.open-drum-feed",
				Name:        "open drum feed",
				Kind:        model.ControlAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.accept-hot-effluent"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.establish-level",
				Name:        "establish level",
				Kind:        model.ProtectAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.open-drum-feed"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.raise-steam",
				Name:        "raise steam",
				Kind:        model.RecoverAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.establish-level"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "steam.control-drum",
				Name:        "control drum",
				Kind:        model.ObserveAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.raise-steam"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.verify-quality",
				Name:        "verify quality",
				Kind:        model.ControlAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.control-drum"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.open-export",
				Name:        "open export",
				Kind:        model.ProtectAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.verify-quality"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "steam.balance-header",
				Name:        "balance header",
				Kind:        model.RecoverAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.open-export"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.track-energy",
				Name:        "track energy",
				Kind:        model.ObserveAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.balance-header"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.protect-low-level",
				Name:        "protect low level",
				Kind:        model.ControlAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.track-energy"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "steam.protect-high-pressure",
				Name:        "protect high pressure",
				Kind:        model.ProtectAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.protect-low-level"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.close-export",
				Name:        "close export",
				Kind:        model.RecoverAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.protect-high-pressure"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.blowdown-drum",
				Name:        "blowdown drum",
				Kind:        model.ObserveAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.close-export"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "steam.cool-exchanger",
				Name:        "cool exchanger",
				Kind:        model.ControlAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.blowdown-drum"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.restore-drum",
				Name:        "restore drum",
				Kind:        model.ProtectAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.cool-exchanger"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.publish-recovery",
				Name:        "publish recovery",
				Kind:        model.RecoverAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.restore-drum"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "steam.archive-balance",
				Name:        "archive balance",
				Kind:        model.ObserveAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.publish-recovery"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "steam.release-permit",
				Name:        "release permit",
				Kind:        model.ControlAction,
				Equipment:   "waste-heat-boiler",
				Requires:    []string{"steam.archive-balance"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
