package cooling

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "cooling",
		Actions: []model.ActionDefinition{
			{
				ID:          "cooling.verify-refrigerant",
				Name:        "verify refrigerant",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"steam.publish-recovery"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "cooling.start-circulation",
				Name:        "start circulation",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.verify-refrigerant"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.open-chiller",
				Name:        "open chiller",
				Kind:        model.ProtectAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.start-circulation"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.establish-duty",
				Name:        "establish duty",
				Kind:        model.RecoverAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.open-chiller"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "cooling.trim-temperature",
				Name:        "trim temperature",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.establish-duty"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.track-condensate",
				Name:        "track condensate",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.trim-temperature"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.request-separation",
				Name:        "request separation",
				Kind:        model.ProtectAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.track-condensate"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "cooling.protect-low-flow",
				Name:        "protect low flow",
				Kind:        model.RecoverAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.request-separation"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.protect-high-pressure",
				Name:        "protect high pressure",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.protect-low-flow"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.shed-optional-load",
				Name:        "shed optional load",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.protect-high-pressure"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "cooling.hold-condensing",
				Name:        "hold condensing",
				Kind:        model.ProtectAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.shed-optional-load"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.close-chiller",
				Name:        "close chiller",
				Kind:        model.RecoverAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.hold-condensing"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.drain-exchanger",
				Name:        "drain exchanger",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.close-chiller"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "cooling.restore-duty",
				Name:        "restore duty",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.drain-exchanger"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.publish-cooling",
				Name:        "publish cooling",
				Kind:        model.ProtectAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.restore-duty"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.archive-duty",
				Name:        "archive duty",
				Kind:        model.RecoverAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.publish-cooling"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "cooling.renew-availability",
				Name:        "renew availability",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.archive-duty"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "cooling.release-cooling",
				Name:        "release cooling",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-condenser",
				Requires:    []string{"cooling.renew-availability"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
