package converter

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "converter",
		Actions: []model.ActionDefinition{
			{
				ID:          "converter.verify-catalyst",
				Name:        "verify catalyst",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"compressor.publish-machine"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "converter.open-preheat",
				Name:        "open preheat",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.verify-catalyst"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.warm-bed-one",
				Name:        "warm bed one",
				Kind:        model.ProtectAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.open-preheat"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.warm-bed-two",
				Name:        "warm bed two",
				Kind:        model.RecoverAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.warm-bed-one"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "converter.warm-bed-three",
				Name:        "warm bed three",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.warm-bed-two"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.admit-synthesis-gas",
				Name:        "admit synthesis gas",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.warm-bed-three"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.control-hotspot",
				Name:        "control hotspot",
				Kind:        model.ProtectAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.admit-synthesis-gas"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "converter.balance-quench",
				Name:        "balance quench",
				Kind:        model.RecoverAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.control-hotspot"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.recover-effluent",
				Name:        "recover effluent",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.balance-quench"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.measure-conversion",
				Name:        "measure conversion",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.recover-effluent"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "converter.request-steam",
				Name:        "request steam",
				Kind:        model.ProtectAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.measure-conversion"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.reduce-feed",
				Name:        "reduce feed",
				Kind:        model.RecoverAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.request-steam"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.cool-bed",
				Name:        "cool bed",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.reduce-feed"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "converter.isolate-reactor",
				Name:        "isolate reactor",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.cool-bed"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.equalize-bed",
				Name:        "equalize bed",
				Kind:        model.ProtectAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.isolate-reactor"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.restore-profile",
				Name:        "restore profile",
				Kind:        model.RecoverAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.equalize-bed"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "converter.publish-bed-state",
				Name:        "publish bed state",
				Kind:        model.ObserveAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.restore-profile"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "converter.archive-campaign",
				Name:        "archive campaign",
				Kind:        model.ControlAction,
				Equipment:   "ammonia-converter",
				Requires:    []string{"converter.publish-bed-state"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
