package journal

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "journal",
		Actions: []model.ActionDefinition{
			{
				ID:          "journal.open-segment",
				Name:        "open segment",
				Kind:        model.ObserveAction,
				Equipment:   "operation-journal",
				Requires:    []string{"campaign.accept-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "journal.allocate-event",
				Name:        "allocate event",
				Kind:        model.ControlAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.open-segment"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.encode-payload",
				Name:        "encode payload",
				Kind:        model.ProtectAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.allocate-event"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.append-record",
				Name:        "append record",
				Kind:        model.RecoverAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.encode-payload"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "journal.flush-record",
				Name:        "flush record",
				Kind:        model.ObserveAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.append-record"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.rotate-segment",
				Name:        "rotate segment",
				Kind:        model.ControlAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.flush-record"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.write-snapshot",
				Name:        "write snapshot",
				Kind:        model.ProtectAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.rotate-segment"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "journal.verify-checksum",
				Name:        "verify checksum",
				Kind:        model.RecoverAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.write-snapshot"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.replay-segment",
				Name:        "replay segment",
				Kind:        model.ObserveAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.verify-checksum"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.project-cycle",
				Name:        "project cycle",
				Kind:        model.ControlAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.replay-segment"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "journal.project-equipment",
				Name:        "project equipment",
				Kind:        model.ProtectAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.project-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.project-incident",
				Name:        "project incident",
				Kind:        model.RecoverAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.project-equipment"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.compact-segment",
				Name:        "compact segment",
				Kind:        model.ObserveAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.project-incident"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "journal.recover-tail",
				Name:        "recover tail",
				Kind:        model.ControlAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.compact-segment"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.publish-offset",
				Name:        "publish offset",
				Kind:        model.ProtectAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.recover-tail"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.archive-segment",
				Name:        "archive segment",
				Kind:        model.RecoverAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.publish-offset"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "journal.renew-writer",
				Name:        "renew writer",
				Kind:        model.ObserveAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.archive-segment"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "journal.audit-storage",
				Name:        "audit storage",
				Kind:        model.ControlAction,
				Equipment:   "operation-journal",
				Requires:    []string{"journal.renew-writer"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
