package campaign

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "campaign",
		Actions: []model.ActionDefinition{
			{
				ID:          "campaign.accept-cycle",
				Name:        "accept cycle",
				Kind:        model.ObserveAction,
				Equipment:   "production-cycle",
				Requires:    []string{},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "campaign.reserve-revision",
				Name:        "reserve revision",
				Kind:        model.ControlAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.accept-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.confirm-feed",
				Name:        "confirm feed",
				Kind:        model.ProtectAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.reserve-revision"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.start-lube",
				Name:        "start lube",
				Kind:        model.RecoverAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.confirm-feed"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "campaign.synchronize-shaft",
				Name:        "synchronize shaft",
				Kind:        model.ObserveAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.start-lube"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.raise-pressure",
				Name:        "raise pressure",
				Kind:        model.ControlAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.synchronize-shaft"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.admit-converter",
				Name:        "admit converter",
				Kind:        model.ProtectAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.raise-pressure"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "campaign.begin-reaction",
				Name:        "begin reaction",
				Kind:        model.RecoverAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.admit-converter"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.request-cooling",
				Name:        "request cooling",
				Kind:        model.ObserveAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.begin-reaction"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.begin-condensing",
				Name:        "begin condensing",
				Kind:        model.ControlAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.request-cooling"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "campaign.begin-separation",
				Name:        "begin separation",
				Kind:        model.ProtectAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.begin-condensing"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.verify-product",
				Name:        "verify product",
				Kind:        model.RecoverAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.begin-separation"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.declare-stable",
				Name:        "declare stable",
				Kind:        model.ObserveAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.verify-product"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "campaign.checkpoint-cycle",
				Name:        "checkpoint cycle",
				Kind:        model.ControlAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.declare-stable"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.publish-cycle",
				Name:        "publish cycle",
				Kind:        model.ProtectAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.checkpoint-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.close-cycle",
				Name:        "close cycle",
				Kind:        model.RecoverAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.publish-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "campaign.recover-cycle",
				Name:        "recover cycle",
				Kind:        model.ObserveAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.close-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "campaign.audit-transition",
				Name:        "audit transition",
				Kind:        model.ControlAction,
				Equipment:   "production-cycle",
				Requires:    []string{"campaign.recover-cycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
