package interlock

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "interlock",
		Actions: []model.ActionDefinition{
			{
				ID:          "interlock.collect-equipment",
				Name:        "collect equipment",
				Kind:        model.ObserveAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"analyzer.publish-reading"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "interlock.collect-process",
				Name:        "collect process",
				Kind:        model.ControlAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.collect-equipment"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.evaluate-feed",
				Name:        "evaluate feed",
				Kind:        model.ProtectAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.collect-process"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.evaluate-lube",
				Name:        "evaluate lube",
				Kind:        model.RecoverAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.evaluate-feed"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "interlock.evaluate-pressure",
				Name:        "evaluate pressure",
				Kind:        model.ObserveAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.evaluate-lube"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.evaluate-temperature",
				Name:        "evaluate temperature",
				Kind:        model.ControlAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.evaluate-pressure"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.evaluate-level",
				Name:        "evaluate level",
				Kind:        model.ProtectAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.evaluate-temperature"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "interlock.evaluate-composition",
				Name:        "evaluate composition",
				Kind:        model.RecoverAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.evaluate-level"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.vote-permit",
				Name:        "vote permit",
				Kind:        model.ObserveAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.evaluate-composition"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.issue-trip",
				Name:        "issue trip",
				Kind:        model.ControlAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.vote-permit"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "interlock.issue-unload",
				Name:        "issue unload",
				Kind:        model.ProtectAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.issue-trip"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.latch-cause",
				Name:        "latch cause",
				Kind:        model.RecoverAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.issue-unload"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.reset-latch",
				Name:        "reset latch",
				Kind:        model.ObserveAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.latch-cause"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "interlock.verify-safe-state",
				Name:        "verify safe state",
				Kind:        model.ControlAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.reset-latch"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.restore-permit",
				Name:        "restore permit",
				Kind:        model.ProtectAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.verify-safe-state"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.publish-interlock",
				Name:        "publish interlock",
				Kind:        model.RecoverAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.restore-permit"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "interlock.archive-decision",
				Name:        "archive decision",
				Kind:        model.ObserveAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.publish-interlock"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "interlock.audit-protection",
				Name:        "audit protection",
				Kind:        model.ControlAction,
				Equipment:   "safety-interlock",
				Requires:    []string{"interlock.archive-decision"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
