package compressor

import (
	"github.com/wyw14/cry-164/internal/model"
	"time"
)

func Plan() model.ComponentPlan {
	return model.ComponentPlan{
		Name: "compressor",
		Actions: []model.ActionDefinition{
			{
				ID:          "compressor.verify-lube",
				Name:        "verify lube",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"feed.publish-permit"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 0, Maximum: 100, Unit: "percent"}},
				Timeout:     1 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "compressor.start-lube-pump",
				Name:        "start lube pump",
				Kind:        model.ControlAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.verify-lube"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 1, Maximum: 101, Unit: "percent"}},
				Timeout:     2 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.soak-bearings",
				Name:        "soak bearings",
				Kind:        model.ProtectAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.start-lube-pump"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 2, Maximum: 102, Unit: "percent"}},
				Timeout:     3 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.engage-turning",
				Name:        "engage turning",
				Kind:        model.RecoverAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.soak-bearings"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 3, Maximum: 103, Unit: "percent"}},
				Timeout:     4 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "compressor.verify-suction",
				Name:        "verify suction",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.engage-turning"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 4, Maximum: 104, Unit: "percent"}},
				Timeout:     5 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.start-driver",
				Name:        "start driver",
				Kind:        model.ControlAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.verify-suction"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 5, Maximum: 105, Unit: "percent"}},
				Timeout:     6 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.synchronize-speed",
				Name:        "synchronize speed",
				Kind:        model.ProtectAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.start-driver"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 6, Maximum: 106, Unit: "percent"}},
				Timeout:     7 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "compressor.open-discharge",
				Name:        "open discharge",
				Kind:        model.RecoverAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.synchronize-speed"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 7, Maximum: 107, Unit: "percent"}},
				Timeout:     8 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.enable-antisurge",
				Name:        "enable antisurge",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.open-discharge"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 8, Maximum: 108, Unit: "percent"}},
				Timeout:     9 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.raise-load",
				Name:        "raise load",
				Kind:        model.ControlAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.enable-antisurge"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 9, Maximum: 109, Unit: "percent"}},
				Timeout:     10 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "compressor.hold-pressure",
				Name:        "hold pressure",
				Kind:        model.ProtectAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.raise-load"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 10, Maximum: 110, Unit: "percent"}},
				Timeout:     11 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.sample-vibration",
				Name:        "sample vibration",
				Kind:        model.RecoverAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.hold-pressure"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 11, Maximum: 111, Unit: "percent"}},
				Timeout:     12 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.sample-temperature",
				Name:        "sample temperature",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.sample-vibration"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 12, Maximum: 112, Unit: "percent"}},
				Timeout:     13 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "compressor.trip-driver",
				Name:        "trip driver",
				Kind:        model.ControlAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.sample-temperature"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 13, Maximum: 113, Unit: "percent"}},
				Timeout:     14 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.open-recycle",
				Name:        "open recycle",
				Kind:        model.ProtectAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.trip-driver"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 14, Maximum: 114, Unit: "percent"}},
				Timeout:     15 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.coast-down",
				Name:        "coast down",
				Kind:        model.RecoverAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.open-recycle"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 15, Maximum: 115, Unit: "percent"}},
				Timeout:     16 * time.Second,
				Recoverable: false,
			},
			{
				ID:          "compressor.restore-session",
				Name:        "restore session",
				Kind:        model.ObserveAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.coast-down"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 16, Maximum: 116, Unit: "percent"}},
				Timeout:     17 * time.Second,
				Recoverable: true,
			},
			{
				ID:          "compressor.publish-machine",
				Name:        "publish machine",
				Kind:        model.ControlAction,
				Equipment:   "recycle-compressor",
				Requires:    []string{"compressor.restore-session"},
				Thresholds:  []model.Threshold{{Name: "operating-band", Minimum: 17, Maximum: 117, Unit: "percent"}},
				Timeout:     18 * time.Second,
				Recoverable: true,
			},
		},
	}
}
